### ISSUE TITLE
Bug due to .jpk software update

### ISSUE THREAD

**Issue by AnRo20** [Rufman91/ForceMapAnalysis#12]
I just found a bug due to the .jpk software update:
- The `velocity` value is not found in the `header.properties` in the old software

In the moment I am trying to find the document in the old software version where the velocity is stored.

**Comment by Rufman91** [comment]
okay, good catch. Once you've found out how its called in the older versions, you/we can add a conditional statement that checks for softwareversion :)

**Comment by AnRo20** [comment]
I can´t find the entry in the old software version. I am looking for a work around means calculating the speed based on the other information given in the `header.properties`. 
We could also contact jpk/Bruker!?

**Comment by Rufman91** [comment]
Fixed it by calculating vertical tip velocity from Z-length divided by ExtensionTime instead. Only gets executed in the case that the line containing the tip velocity cannot be found as is the case for older jpk-software versions.

**Comment by AnRo20** [comment]
Nice bug fix. I tried something similar but I guess a bit more complicated.  I thought about an `if` condition based on the software version in case that we stumble over some other bugs due to the software update. Additionally, we could give also the retraction velocity as an property by calculating it.
What do you think?

**Comment by Rufman91** [comment]
@AnRo20 

Hey, I suppose something like that would be nice to have. We really could make the effort to read out all the information we get from the header. For the sake of readability we should outsource the header-readout to its own method that gets passed down just the fullfile-string of the header and then reads out all the information, with a switch or an if-statement for software version. This way we can fix future problems much more easily, i.e. should they completely change how the header is written in future releases. What we would need to properly do it though, is a jpk-force-map file with different extend- and retract- speeds to see how they write that into the header. If we don't have one at hand, we could also calculate the two velocities from length/time from the get-go, similar to what i did in the original fix.

Maybe we can get some of it done today during the exam?

**Comment by Rufman91** [comment]
@AnRo20

**Comment by Rufman91** [comment]
Closing this issue, since most of the things we mention here are now implemented :)
