### ISSUE TITLE
Create function to sort force maps by properties

### ISSUE THREAD

**Issue by AnRo20** [Rufman91/ForceMapAnalysis#15]
As just discussed, here comes the issue for the sort by property function

**Comment by AnRo20** [comment]
I have a running function for my SMFS branch. Quite rudimentary but running. Could serve as a base for further developements!

**Comment by Rufman91** [comment]
Nice, I'll have a look at it in the evening
@AnRo20

**Comment by AnRo20** [comment]
@Rufman91: Great, let me know if you need some assistance or if you just want to discuss.

**Comment by AnRo20** [comment]
The function is running smoothly, allowing to sort for different properties - i.e. starting and end dated, substrate, environmental conditions, velocity. Further selection properties will follow.
The function is called `SMFS_print_sort_specific`
