### ISSUE TITLE
Bug in the velocity read out

### ISSUE THREAD

**Issue by AnRo20** [Rufman91/ForceMapAnalysis#21]
I found a bug in the velocity read out. After looking into the `header properties` of some force curves and comparing them with the jpk software I think the origin of the problem lies by jpk. The given 
 `force-scan-map.settings.force-settings.start-option.velocity=` is not the same as if calculating it by using `force-scan-map.settings.force-settings.relative-z-start=` and `force-scan-map.settings.force-settings.extend-scan-time=`.

I suggest to **always** calculate the velocity rather than taking the value given by the `velocity` entry. We are doing this already for the old software version.
**I have not changed it yet** to avoid any problems with `pulling` afterwards. I propose to change it in the `master` first and then distributing it to the other versions. 
**Maybe we can do this after the Institute meeting on Tuesday.**

**Comment by Rufman91** [comment]
Fixed and pushed to all branches 👍  (except microrheology)
