### ISSUE TITLE
spelling mistake in function "writedata" ?

### ISSUE THREAD

**Issue by maerci** [Rufman91/ForceMapAnalysis#22]
I wonder if in this whole function "writedata" it should be "HeightDataDirectory" like in function "load_force_curves" or really "HeighDataDirectory" - or does this spelling mistake (?) does not affect the outcome?

function [HeadHeight ,Force,spring_constant,sensitivity]=...
                writedata(HeaderFileDirectory,SegmentHeaderFileDirectory,...
                **HeighDataDirectory**,vDelfDataDirectory,HHType)

...

**Comment by Rufman91** [comment]
Yes, this is indeed a spelling mistake. It does not affect functionality though so I'll leave it up to you, if you want to fix it :)
