### ISSUE TITLE
Error message E=Experiment

### ISSUE THREAD

**Issue by maerci** [Rufman91/ForceMapAnalysis#29]
![error_dropoutnetfinal_20210326](https://user-images.githubusercontent.com/79519194/114425951-daf9ef80-9bb9-11eb-9ab8-eee3b6f174a1.JPG)

I get this error when I want to execute E=Experiment

**Comment by Rufman91** [comment]
Look into the source codes directory and check if all **subfolders** are added to the matlab path. The file MATLAB couldn't find here is in the subfolder NeuralNets.

@maerci

**Comment by maerci** [comment]
Gracias!
