### ISSUE TITLE
Weird variable in AFMImage.parse_unit_scale

### ISSUE THREAD

**Issue by AnRo20** [Rufman91/ForceMapAnalysis#33]
@Rufman91 
Function :  [Xmultiplier,Xunit,~] = AFMImage.parse_unit_scale(1e+9,'nm',1); 
The Xunit variable gives a weird 'Gnm'. I do not know where the 'G' is coming from and if this is needed for some other code!?

**Comment by AnRo20** [comment]
Ok, I had a look on it again. It is not weird considering that 1e+9 is used in the function and - surprise, surprise - giga is the prefix used for it... 
I wanted to use it as `sprintf` to label axes which is not possible, but not an important thing to do.

**Comment by Rufman91** [comment]
Ahhh yes, the method is designed to take in SI-base-units and add the proper prefix. this way all data can be stored in base unit and only be scaled in visualization-related methods.
LG
