### ISSUE TITLE
ID number for each force curve

### ISSUE THREAD

**Issue by AnRo20** [Rufman91/ForceMapAnalysis#7]
I would like tot discuss the idea of implementing an **ID numbe**r for each force curve uploaded. I have to admit I am not absolutely convinced about but still would like to discuss it.

**Comment by Rufman91** [comment]
Interesting idea, we should discuss it in our merging session.

**Comment by AnRo20** [comment]
Great. Let´s do this.

**Comment by Rufman91** [comment]
Implemented! Good Job!

**Comment by Rufman91** [comment]
@AnRo20 
This idea turned out to be just the thing i needed to properly implement multithreading during ForceMap loading and unpacking. Again, great input!
