### ISSUE TITLE
function update_NumFiles(obj)

### ISSUE THREAD

**Issue by AnRo20** [Rufman91/ForceMapAnalysis#8]
I witnessed that adding new data led to a `NumFiles` variable only accounting for the added data but not for the current data. I created a simple function `update_NumFiles` fixing this problem. 
@Rufman91 **shall I add it to the **constructor methods**?** If yes, do I have to take some special considerations into account by doing that?

**Comment by Rufman91** [comment]
Hey, the issue with the file count not updating and related issues has already been solved in the master branch. So to resolve it on your side we'll just need to figure out what we wanted to do anyway: merging our branches without losing any of our work (maybe with the cherry picking function you suggested)

**Comment by AnRo20** [comment]
Ok, that is good but looks like we need to do a merging session otherwise we will re-invent the wheel more often in the future. Let me know when you have time for the merging party!

**Comment by Rufman91** [comment]
WE DID IT!
