### ISSUE TITLE
Experiment.add_data

### ISSUE THREAD

**Issue by Rufman91** [Rufman91/ForceMapAnalysis#9]
Still doesn't work. copying from SaveCopy to actual output just doesn't happen.

LOOK INTO IT!

**Comment by Rufman91** [comment]
Solved issue with a workaround. Function now works as safely as intended, but the Experiments workplace variable needs to be overwritten with the output of .add_data.

>> E = E.add_data;

will lead to the desired behaviour

>> E.add_data

will just store the Experiment with the added files in  the matlab variable 'ans' and inevitably overwritten at some point

function by default now issues a warning, reminding the user to adhere to the correct syntax.

**Comment by AnRo20** [comment]
Bug found. After unsuccessful use of the function due to corrupt (unfinished) force map rerun of the function leads to no added force maps, even if they are not corrupted.

**Comment by Rufman91** [comment]
Implement pls:
Fix: add two steps to catch section in add_data: 
- close all open files
- delete all temporary folders

**Comment by Rufman91** [comment]
Bug fixed. Awaiting granting of pull from master to SMFS
